- src/main/java/org/maxgamer/quickshop/Command/QS.java
add "p.getFacing().getOppositeFace()"
> fixed create shopping sign bug.

- src/main/java/org/maxgamer/quickshop/Util/Util.java
* Dev mode will get from config every call, which lookup a `HashMap`
* `location3DEqual` will check world every time even the only caller is double chest, which won't be in the different world.
* Add one more helper method to check the block `int` coord with final static to let inline.
> Optimize dev mode check and location3DEqual

- src/main/java/org/maxgamer/quickshop/Util/MsgUtil.java
Must have missed this in my first go through
> Update the english in MsgUtil

- src/main/java/org/maxgamer/quickshop/Event/ShopCreateEvent.java
- src/main/java/org/maxgamer/quickshop/Event/ShopDeleteEvent.java
- src/main/java/org/maxgamer/quickshop/Event/ShopDisplayItemDespawnEvent.java
- src/main/java/org/maxgamer/quickshop/Event/ShopDisplayItemSpawnEvent.java
- src/main/java/org/maxgamer/quickshop/Event/ShopInventoryPreviewEvent.java
- src/main/java/org/maxgamer/quickshop/Event/ShopLoadEvent.java
- src/main/java/org/maxgamer/quickshop/Event/ShopModeratorChangedEvent.java
- src/main/java/org/maxgamer/quickshop/Event/ShopPreCreateEvent.java
- src/main/java/org/maxgamer/quickshop/Event/ShopPriceChangedEvent.java
- src/main/java/org/maxgamer/quickshop/Event/ShopPurchaseEvent.java
- src/main/java/org/maxgamer/quickshop/Event/ShopSignUpdatedEvent.java
- src/main/java/org/maxgamer/quickshop/Event/ShopSuccessPurchaseEvent.java
- src/main/java/org/maxgamer/quickshop/Event/ShopUnloadEvent.java
- src/main/java/org/maxgamer/quickshop/Event/ShopUpdateEvent.java
According bukkit.gamepedia.com the method "getHandlerList" must be static. This should solve another NullPointerException problem
https://bukkit.gamepedia.com/Event_API_Reference#Creating_Custom_Events
> make "getHandlerList" static

- src/main/java/org/maxgamer/quickshop/Shop/ShopManager.java
I'm sorry but this was another one I urgently want to fix.
I've tested this. as you said this wasn't a bug. and now fixed it!
> Differentiated cancel message

- src/main/java/org/maxgamer/quickshop/Shop/ShopManager.java
rather than output both cancel-purchase and cancel-create, just let player know that player isn't looking at shop.
> Reduced repeating codes

- src/main/java/org/maxgamer/quickshop/Listeners/PlayerListener.java
- src/main/java/org/maxgamer/quickshop/Shop/ShopManager.java
have tested over and over. omg there was more!
> Specified more error output with 'all' feature

- src/main/java/org/maxgamer/quickshop/Shop/DisplayItem.java
- src/main/java/org/maxgamer/quickshop/Shop/RealDisplayItem.java
> Fixed shop.display-item-use-name work properly

- .gitignore
- src/main/java/org/maxgamer/quickshop/Command/SubCommands/SubCommand_Create.java
- src/main/java/org/maxgamer/quickshop/Util/Util.java
> Fixing create command and ender chest issues

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/performance.md
This P.R. for this #223 situations.
> Add new feature template

- src/main/java/org/maxgamer/quickshop/Economy/Economy_Vault.java
> Fix economy console spam bug

- src/main/java/org/maxgamer/quickshop/Command/SubCommands/SubCommand_Price.java
- src/main/java/org/maxgamer/quickshop/QuickShop.java
- src/main/java/org/maxgamer/quickshop/Shop/ShopManager.java
- src/main/java/org/maxgamer/quickshop/Util/MsgUtil.java
> Fix decimal format bug

- src/main/java/org/maxgamer/quickshop/Listeners/BlockListener.java
- src/main/java/org/maxgamer/quickshop/Listeners/PlayerListener.java
Fixes: https://github.com/Ghost-chu/QuickShop-Reremake/issues/268
> Updates both signs for double chest shop.

- src/main/java/org/maxgamer/quickshop/Listeners/BlockListener.java
org.bukkit.block.Sign is a BlockState instead of CraftBlock.
> Fixes BlockState casting

- .idea/QuickShop-Reremake.iml
- src/main/java/org/maxgamer/quickshop/QuickShop.java
Clearer messages when detecting CatServer
> CatServer Support Clarification

- src/main/java/org/maxgamer/quickshop/listener/PlayerListener.java
The shop purchase cancel message should not be the same as the shop creatin cancel message.
> Shop purchase cancelled message fix

- src/main/java/org/maxgamer/quickshop/QuickShop.java
- src/main/java/org/maxgamer/quickshop/util/Util.java
- src/main/resources/config.yml
Added possibility to show enchantment names instead of "Enchanted Book" in sign.
Added config entry to enabled this (disabled by default).
> Enchant names

- src/main/resources/plugin.yml
Is it okay to list OpenInv as softdepend? (Missing from new list but was listed in old softdepend....)
Also removed some parts of old note about dependencies that are now in the new list...
Is the thing with Herochat done? If yes ill remove this note too.
> Some language improvements to plugin.yml

- pom.xml
- src/main/java/org/maxgamer/quickshop/util/reporter/error/RollbarErrorReporter.java
- src/main/resources/lang/no-NO/messages.json
- src/main/resources/lang/pl-PL/messages.json
* 4.0.8.3 (#987) (#994)
post back to master
* Create .bettercodehub.yml
* Create crowdin-merge.yml
* Update crowdin-merge.yml
* Update crowdin-merge.yml
* New Crowdin updates (#995)
* New translations messages.json (Russian)
* New translations messages.json (Japanese)
* New translations messages.json (Vietnamese)
* New translations messages.json (Chinese Traditional)
* New translations messages.json (Chinese Simplified)
* New translations messages.json (Ukrainian)
* New translations messages.json (Turkish)
* New translations messages.json (Swedish)
* New translations messages.json (Serbian (Cyrillic))
* New translations messages.json (Portuguese)
* New translations messages.json (Polish)
* New translations messages.json (Norwegian)
* New translations messages.json (Dutch)
* New …
> 4.0.8.5 (#1036)

- pom.xml
- src/main/java/org/maxgamer/quickshop/shop/ContainerShop.java
* 4.0.8.3 (#987) (#994)
post back to master
* Create .bettercodehub.yml
* Create crowdin-merge.yml
* Update crowdin-merge.yml
* Update crowdin-merge.yml
* New Crowdin updates (#995)
* New translations messages.json (Russian)
* New translations messages.json (Japanese)
* New translations messages.json (Vietnamese)
* New translations messages.json (Chinese Traditional)
* New translations messages.json (Chinese Simplified)
* New translations messages.json (Ukrainian)
* New translations messages.json (Turkish)
* New translations messages.json (Swedish)
* New translations messages.json (Serbian (Cyrillic))
* New translations messages.json (Portuguese)
* New translations messages.json (Polish)
* New translations messages.json (Norwegian)
* New translations messages.json (Dutch)
* New …
> 4.0.8.6 (#1038)

- src/main/java/org/maxgamer/quickshop/command/subcommand/SubCommand_Empty.java
What is this old note: "TODO: 24/11/2019 Send message about that issue."?
Should i remove it?
> Questions in SubCommand_Empty.java

- src/main/java/org/maxgamer/quickshop/command/subcommand/SubCommand_CleanGhost.java
Can you please explain "Starting checking the shop be ghost, all does not exist shop will be removed..." a little better...not sure what it means... (line 57)
What do you mean by "posting" (to main server thread)? (line 110)
What exactly is meant by "disallow create the shop"? (line 117) (Maybe that its not allowed to create a shop in this location?)
> Improvements in SubCommand_CleanGhost.java

- src/main/java/org/maxgamer/quickshop/command/subcommand/SubCommand_Info.java
What do you mean by "nostock selling shops"?
> Improvements in SubCommand_Info.java

- .github/workflows/maven.yml
Shouldn't this be JDK 16? (Because it says java-version: '16'...)
> Wrong JDK name fixed

- src/main/java/org/maxgamer/quickshop/integration/griefprevention/GriefPreventionIntegration.java
Eliminated duplicated Code. Changed variables names. Fixed problem with the Grief Prevention untrust handler (it would remove shops that were not related to the claim that someone untrusted other person). Reverted changes made by Ghost_chu that wouldn't make sense in the context of GriefPrevention (now when a claim is unclaimed or expired all shops inside it will me deleted as well).
Now everything should be fine :p
> Fixed many things with the Grief Prevention Integration
